[build]
publish = "public"
command = "make production"

[build.environment]
HUGO_VERSION = "0.111.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "make preview"

[context.deploy-preview.environment]
HUGO_VERSION = "0.111.3"

[context.branch-deploy]
command = "make branch"

[context.branch-deploy.environment]
HUGO_VERSION = "0.111.3"
